### ISSUE TITLE
Password reset process not working

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#1]
If I enter the incorrect password, I get an error message that I can't read as the words are cut off. 

![image](https://user-images.githubusercontent.com/3986896/82199313-6fe66100-98f5-11ea-9a48-c3d510aefa9e.png)

If I ask for a password reset, I am prompted to enter my email, then get a error message

![image](https://user-images.githubusercontent.com/3986896/82199415-8f7d8980-98f5-11ea-9c1d-b0236587d502.png)

**Comment by ClairePA** [comment]
Still can't reset my password. I successfully get an email with a button to reset it but clicking the email button gives me the following error:
![image](https://user-images.githubusercontent.com/3986896/96109869-0df74b00-0ed7-11eb-9ddb-ddbf9d391ee0.png)

**Comment by elrashid24** [comment]
Resolved:
![image](https://user-images.githubusercontent.com/46327483/98071756-6b295100-1e32-11eb-8b32-3a7ced7fa4c9.png)
![image](https://user-images.githubusercontent.com/46327483/98071802-87c58900-1e32-11eb-91e5-b7f6b8c1e576.png)
![image](https://user-images.githubusercontent.com/46327483/98071836-97dd6880-1e32-11eb-9ac6-917871bd44d7.png)

**Comment by ClairePA** [comment]
Resolved.
