### ISSUE TITLE
Drop down list for library name should be the library key only and not the full URL

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#10]
The drop down list of libraries in the editor shows the full URL. This should be changed to list the library keys.  The full URL is not intuitive. 

![image](https://user-images.githubusercontent.com/3986896/84058030-8772b000-a9b0-11ea-9238-0f0d272613b8.png)

**Comment by elrashid24** [comment]
Resolved 
![image](https://user-images.githubusercontent.com/46327483/98062884-d831ec00-1e1c-11eb-94a2-c049c6713eca.png)

**Comment by ClairePA** [comment]
Confirmed fixed for the editor, but not the viewer on the Home page

![image](https://user-images.githubusercontent.com/3986896/98809571-a967d700-2415-11eb-8ffc-d81b4f68be3b.png)

**Comment by elrashid24** [comment]
Resolved in home page as well

**Comment by ClairePA** [comment]
Home page behaviour is odd, why is this not a drop down when there is a fully functional drop down on the editor page? You first see instructions to enter the library key when you should really select the library from a list. 
![image](https://user-images.githubusercontent.com/3986896/107068341-6761ed80-67d8-11eb-9fe2-5d6a8cdae0fc.png)
If you click on the box then you get a complete list of libraries.
![image](https://user-images.githubusercontent.com/3986896/107068411-7c3e8100-67d8-11eb-90b6-a27cab52b659.png)

However, if I select a library then change my mind, I can no longer see the other libraries. 
![image](https://user-images.githubusercontent.com/3986896/107068466-937d6e80-67d8-11eb-8776-a1aea3486cf9.png)

All we really need here is a normal drop down populated with all available libraries.

**Comment by elrashid24** [comment]
Sounds good-it's an editable select, but I will change it to a regular drop down list with no option to type in a library

**Comment by ClairePA** [comment]
Confirmed fixed.
