### ISSUE TITLE
Editor button is not underlined when on the editor page

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#11]
If I select 'Libraries' I see the button underlined in the top menu.

![image](https://user-images.githubusercontent.com/3986896/84058410-1aabe580-a9b1-11ea-91c7-565eb1d5b001.png)

This works for all other buttons except the editor.

![image](https://user-images.githubusercontent.com/3986896/84058476-31ead300-a9b1-11ea-996c-f7b435cdf220.png)

**Comment by ClairePA** [comment]
Now only the Home button is underlined when selected. None of the other buttons indicate which page you are on.

**Comment by elrashid24** [comment]
Resolved, all tabs should be highlighted when user is on the page.

**Comment by ClairePA** [comment]
Confirmed fixed. Close
