### ISSUE TITLE
Can't use the editor if not logged in

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#13]
The editor should be available to all users and should not require a login. Currently you get the following error.

![image](https://user-images.githubusercontent.com/3986896/96107007-c8854e80-0ed3-11eb-95a7-471f523d7e28.png)

**Comment by elrashid24** [comment]
Resolved (user not logged in)
![image](https://user-images.githubusercontent.com/46327483/98062884-d831ec00-1e1c-11eb-94a2-c049c6713eca.png)

**Comment by ClairePA** [comment]
Confirmed fixed
