### ISSUE TITLE
Replace library admin with library owner  

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#14]
The library owner role is call admin which is confusing since it is the same name as the top level admin. Please can we change this to owner? 
![image](https://user-images.githubusercontent.com/3986896/96747405-25936f80-13c0-11eb-8568-df220af43ddd.png)

**Comment by elrashid24** [comment]
Library owners are defined when creating the Library (they don't actually get saved as "members")
There is no "role" of owner.
After saving the user as the owner (done at the Library table) there is no need to add them as a member. 
-We can discuss naming/roles for "Admin" users (might not be a need for that role at all)

**Comment by ClairePA** [comment]
Discussed and agreed current process. Close.
