### ISSUE TITLE
Once a library has been chosen moving to other functions should keep the selection

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#16]
Steps to recreate:
I navigate to 'my libraries' and select 'core3'
I then select 'my monomers' and the library defaults to the first one on the list 'test 1'. 

Basically I have to keep selecting the right library as I navigate around the UI. I want it to remember my selection and default to that one.

**Comment by elrashid24** [comment]
See comment on Issue #13

**Comment by ClairePA** [comment]
#13 not relevant. Issue remains.

**Comment by elrashid24** [comment]
Resolved

**Comment by ClairePA** [comment]
Confirmed resolved. Close.
