### ISSUE TITLE
Private libraries are visible in the 'public libraries' list

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#17]
There are 2 options to fix this:

Private libraries should only be visible under 'my libraries'
or
The title of 'public libraries' should be replaced by 'libraries' and show all the libraries the user has access to. 

![image](https://user-images.githubusercontent.com/3986896/97161452-c2199100-1775-11eb-8899-24d4c44ca9cb.png)

**Comment by elrashid24** [comment]
Resolved (3 total libraries, 2 are Public, both are published)
![image](https://user-images.githubusercontent.com/46327483/98070292-dd983200-1e2e-11eb-9e71-cdee0062cfb5.png)
![image](https://user-images.githubusercontent.com/46327483/98070313-ea1c8a80-1e2e-11eb-97d0-e6201861df21.png)

**Comment by ClairePA** [comment]
Confirmed fixed.
