### ISSUE TITLE
The My Monomers page can display different libraries

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#18]
It should not be possible to display different monomer libraries on the same page. The lower box should display the information for the library chosen at the top of the page.

![image](https://user-images.githubusercontent.com/3986896/97164401-f727e280-1779-11eb-9935-0dbcd28689e9.png)

**Comment by elrashid24** [comment]
This feature was added so that users can compare active& draft monomers between different libraries. Can be removed if not needed.

**Comment by ClairePA** [comment]
I don't think it is needed. It will cause more confusion than be helpful.

**Comment by elrashid24** [comment]
Resolved

**Comment by ClairePA** [comment]
Confirmed fixed.
