### ISSUE TITLE
There is a non-functional 'publish library' button in the public libraries page 

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#19]
When I am on the public libraries page I can see unpublished libraries (which I shouldn't be able to see). 

I can also see a 'publish libraries' button. If I click this, nothing happens. The button should not be visible. 

![image](https://user-images.githubusercontent.com/3986896/97474419-ff337e00-1943-11eb-86ce-8032afdb26ba.png)

**Comment by elrashid24** [comment]
Resolved:
![image](https://user-images.githubusercontent.com/46327483/98070337-f86aa680-1e2e-11eb-916e-51387b6e4607.png)

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
