### ISSUE TITLE
Users that are not logged on can't see published, public libraries

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#20]
There are currently 2 public, published libraries. 
![image](https://user-images.githubusercontent.com/3986896/97737078-713acd00-1ad4-11eb-9017-ed0bac252e08.png)

If I logout, I can't see them. 

![image](https://user-images.githubusercontent.com/3986896/97737179-962f4000-1ad4-11eb-9058-ee7562a80b60.png)

**Comment by elrashid24** [comment]
![image](https://user-images.githubusercontent.com/46327483/98017479-523a8480-1dcd-11eb-90ec-3e55c24fb9c7.png)

Resolved

**Comment by elrashid24** [comment]
![image](https://user-images.githubusercontent.com/46327483/98017906-e9074100-1dcd-11eb-9950-4936c29b4ee7.png)
Resolved

**Comment by ClairePA** [comment]
Confirmed fixed.
