### ISSUE TITLE
A new sysadmin account can't log on

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#21]
I create a sys admin account
![image](https://user-images.githubusercontent.com/3986896/97737413-e0b0bc80-1ad4-11eb-8241-57861792ebfe.png)
When they try to log on they get the following message:
![image](https://user-images.githubusercontent.com/3986896/97737525-0b027a00-1ad5-11eb-8526-0be34c4cf723.png)

**Comment by elrashid24** [comment]
Current user is not a system admin, just a regular admin.  
Non sys-admin users can only log in once they've been assigned to a library (either as a member or owner).

**Comment by ClairePA** [comment]
Agreed different approach. Tested and now works correctly.
