### ISSUE TITLE
A members tab is visible to unlogged in users in the public libraries page

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#22]
The user is presented with an error stating that their session has timed out, so they can't use the members page, but it should not be visible at all. 

![image](https://user-images.githubusercontent.com/3986896/98710395-7ec94000-237b-11eb-8724-3ba2fd5fd4ed.png)

**Comment by elrashid24** [comment]
Resolved

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
