### ISSUE TITLE
The process for creating and publishing a library is cumbersome

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#23]
Please check if I have got this right. To create and publish a library you have to do the following:

1. Navigate to 'My LIbraries' and add a new library
2. Despite the fact that there is a 'published monomers' tab, you can't use this or use any function here to add monomers, you must navigate to 'my monomers' 
3. In 'My monomers' you must make sure you re-select the library you just created as it defaults to the library at the top of the list. 
4. Import or add the monomers you want 
5. You can't publish monomers in this page, you have to go back to the 'My Libraries' page. 
6. Navigate to the 'My libraries' page and reselect the library you want as it has defaulted to the first one on the list and no longer shows the one I am working on. You can't see the monomers you want to publish on this page as it only shows monomers that have already been published and that does not include the ones you have just added. 
7. Publish the library using the 'publish library' button. 

This is not really an obvious workflow. Can we discuss making this clearer?

**Comment by elrashid24** [comment]
Resolved (open to ongoing suggestions)

**Comment by ClairePA** [comment]
Discussed in team meeting. Close.
