### ISSUE TITLE
You have to select a library when editing a monomer

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#24]
I navigate to the 'My monomers' list and click on the '+' button to add a new monomer. The dialogue box asks me to choose a library that this monomer is intended for. The library should already have been chosen in the previous form. Asking the user to select at this stage will cause errors. 

![image](https://user-images.githubusercontent.com/3986896/98807086-0d889c00-2412-11eb-816a-22deb7dc754d.png)

**Comment by elrashid24** [comment]
Resolved

**Comment by ClairePA** [comment]
It is better, but you can still create a monomer even when no library has been selected. 
You get an error once you hit the save button, but you have already entered all the information by then. You should not be allowed to start creating a monomer unless a library has been selected.

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
