### ISSUE TITLE
Logging out doesn't actually log me out 

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#25]
I click on logout
![image](https://user-images.githubusercontent.com/3986896/98811861-69a2ee80-2419-11eb-8db5-ce3c3b9c87f3.png)

Confirm that I want to logout
![image](https://user-images.githubusercontent.com/3986896/98811891-76bfdd80-2419-11eb-92f1-d52583df1b46.png)
I see this page
![image](https://user-images.githubusercontent.com/3986896/98811914-817a7280-2419-11eb-8f65-54a50c7fece6.png)

Then if I click on the Home page I still seem to be logged in. 

![image](https://user-images.githubusercontent.com/3986896/98811960-9525d900-2419-11eb-9ed7-f2ef340c551b.png)

**Comment by elrashid24** [comment]
Resolved

**Comment by ClairePA** [comment]
Agreed, resolved.
