### ISSUE TITLE
Monomers are not validated before saving

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#26]
There are rules for what is an acceptable monomer. e.g. CHEM monomers must be of type undefined PEPTIDES cannot be of type branch etc. There must be enforced when saving and currently they don't seem to be.

**Comment by elrashid24** [comment]
We will be changing the N.A. from a dropdown list back to free text & validating upon save.  Agreed in meeting 1-08-2021.

**Comment by ClairePA** [comment]
Natural analogue box has been removed, check the validation is working correctly.

**Comment by ClairePA** [comment]
Validation is not perfect - it doesn't check the monomer type is compatible with the polymer type e.g. allows the user to make a CHEM monomer a backbone type, but picks up the larger errors. 
Recommend this as good enough.
