### ISSUE TITLE
Can't change password for new user

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#27]
I create a new user, set their password and can successfully use that password to log on. When logged on, I am given the option to change the password as the original one will expire in 3 days. 
I complete the current password/new password boxes and it tells me the current password is incorrect. I have checked a number of times and the password is definitely the same one that successfully logs this account on. 

![image](https://user-images.githubusercontent.com/3986896/99799870-4e2b9800-2b2b-11eb-8fca-3a89b15dae83.png)

**Comment by elrashid24** [comment]
(unable to reset password when given the option to prevent expiration)
	Could not reproduce-I was able to reset password. Perhaps with latest deployment it will work on your environment.

**Comment by ClairePA** [comment]
Appears to be working fine now. Close.
