### ISSUE TITLE
Public library displays library versions that are not real

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#28]
I am not logged in, navigate to the public libraries page and select the core library. It only has one version. When I use the drop-down menu it displays multiple versions. It should only show a single version.

![image](https://user-images.githubusercontent.com/3986896/100083659-a3282080-2e41-11eb-922c-3deb09aaa194.png)

Also, where is version 3? It should not be possible to delete library versions.

**Comment by elrashid24** [comment]
Change to a editable textbox. Agreed in meeting on 1-08-2021.

**Comment by ClairePA** [comment]
Confirmed fixed. Close
