### ISSUE TITLE
Incorrect molfile format in downloaded monomers 

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#29]
I downloaded some monomers from a library as JSON.  I had added the monomers manually to this library. 

The JSON file contained the following where a molfile should be. 

`"molfile":"\u003Cdiv version='6.3' class='JSDraw' app='JSDraw v6.7.0.36000' style='width:800px;height:250px;' bondlength='1.56'\u003E\n\u003Ca i='1' e='N' p='20.436 -4.784'/\u003E\n\u003Ca i='2' e='C' p='19.085 -4.004'/\u003E\n\u003Ca i='3' e='C' p='19.085 -2.444'/\u003E\n\u003Ca i='4' e='C' p='21.787 -4.004'/\u003E\n\u003Ca i='5' e='N' p='21.787 -2.444'/\u003E\n\u003Ca i='6' e='C' p='20.436 -1.664'/\u003E\n\u003Ca i='13' e='N' p='17.734 -4.784'/\u003E\n\u003Ca i='17' e='C' p='16.383 -4.004'/\u003E\n\u003Ca i='19' e='C' p='15.032 -4.784'/\u003E\n\u003Ca i='21' e='O' p='16.383 -2.444'/\u003E\n\u003Ca i='23' e='O' p='23.138 -4.784'/\u003E\n\u003Ca i='25' e='R' p='23.138 -1.664' alias='R1'/\u003E\n\u003Cb i='7' a1='1' a2='2' t='2'/\u003E\n\u003Cb i='8' a1='2' a2='3' t='1'/\u003E\n\u003Cb i='9' a1='1' a2='4' t='1'/\u003E\n\u003Cb i='10' a1='4' a2='5' t='1'/\u003E\n\u003Cb i='11' a1='5' a2='6' t='1'/\u003E\n\u003Cb i='12' a1='6' a2='3' t='2'/\u003E\n\u003Cb i='14' a1='2' a2='13' t='1'/\u003E\n\u003Cb i='18' a1='13' a2='17' t='1'/\u003E\n\u003Cb i='20' a1='17' a2='19' t='1'/\u003E\n\u003Cb i='22' a1='17' a2='21' t='2'/\u003E\n\u003Cb i='24' a1='4' a2='23' t='2'/\u003E\n\u003Cb i='26' a1='5' a2='25' t='1'/\u003E\n\u003C/div\u003E\n"`

**Comment by elrashid24** [comment]
So it looks like the mol file being saved to the DB is different depending on whether the monomer was uploaded or manually added. 
I've modified the code to be able to interpret both formats for next release.
Question:
Does the format itself matter outside of Monomer.org? Essentially, if the system is able to interpret both forms of the file-what other issues might arise outside of Monomer.org?

**Comment by ClairePA** [comment]
Firstly, the structures in both cases must be chemically valid [molfiles](https://en.wikipedia.org/wiki/Chemical_table_file#The_Counts_line_block_specification:). It will be extremely important to users that they are valid in standard chemical packages outside monomer.org as we don't know which software users will have. The molfile is a standard format that has been around for around 30 years and is used by basically all chemical software suppliers. 

You need to use a cheminformatics tool to compare molfiles and find out whether these are the same or not. Sciligence must have one of these. So long as the molfiles are the chemically the same it doesn't matter whether they are not the same in terms of the text. Molfiles capture the way the structure was drawn as well as the chemically significant connections between bonds and atoms, so different text does not equal different structure. You need to understand which differences are significant and which are not.  

If you send me the text that is being created in both cases I can tell you whether it is actually a molfile and whether it is the same structure. Or I recommend [OpenBabel](https://openbabel.org/wiki/Main_Page), but as a cheminformatics supplier Sciligence should have its own way of doing this. 

The text above is **not** a molfile.

**Comment by ClairePA** [comment]
The format when exporting a manually entered library is still not a molfile. I get:
`"molfile":"\u003Cdiv version='6.3' class='JSDraw' app='JSDraw v6.8.0.36850' style='width:800px;height:250px;' bondlength='1.56'\u003E\n\u003Ca i='1' e='C' p='16.588 -5.304'/\u003E\n\u003Ca i='2' e='C' p='15.237 -4.524'/\u003E\n\u003Ca i='3' e='C' p='15.237 -2.964'/\u003E\n\u003Ca i='4' e='C' p='17.939 -4.524'/\u003E\n\u003Ca i='5' e='C' p='17.939 -2.964'/\u003E\n\u003Ca i='6' e='C' p='16.588 -2.184'/\u003E\n\u003Ca i='13' e='R' p='19.290 -2.184' alias='R1'/\u003E\n\u003Cb i='7' a1='1' a2='2' t='2'/\u003E\n\u003Cb i='8' a1='2' a2='3' t='1'/\u003E\n\u003Cb i='9' a1='1' a2='4' t='1'/\u003E\n\u003Cb i='10' a1='4' a2='5' t='2'/\u003E\n\u003Cb i='11' a1='5' a2='6' t='1'/\u003E\n\u003Cb i='12' a1='6' a2='3' t='2'/\u003E\n\u003Cb i='14' a1='5' a2='13' t='1'/\u003E\n\u003C/div\u003E\n"`

If I export as sdf I get an no structure. 

`Unnamed
MolEngine02052117402D

  0  0  0  0  0  0  0  0  0  0999 V2000
M  END`

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
