### ISSUE TITLE
Library browser does not show the monomer structure

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#3]
When I browse the monomers in the browsing window I can't highlight a monomers and see the full structure and other information. 

It should be possible to see the full details. 

![image](https://user-images.githubusercontent.com/3986896/82208880-3c5f0300-9904-11ea-9d99-ee4d3f951591.png)

**Comment by elrashid24** [comment]
Potential workaround: Be able to view monomer structure by hovering over the row.

**Comment by ClairePA** [comment]
Viewing the monomer structure by hovering over the row should be implemented in this release.

**Comment by ClairePA** [comment]
Published monomers page addresses this issue. Close.
