### ISSUE TITLE
Can't use the Home and Editor pages without logging on

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#33]
Any user should be able to access the monomer.org Home and Editor pages without needing to log on. However when I am told that my session has timed out and I need to log in again. 

![image](https://user-images.githubusercontent.com/3986896/104575229-d5d6e400-564e-11eb-8420-3412338b6cce.png)

**Comment by elrashid24** [comment]
Resolved on 1-20-2021

**Comment by ClairePA** [comment]
Resolved. Close.
