### ISSUE TITLE
Later library versions don't appear in the 'My Monomers' page

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#35]
I have a public library with 2 versions.

![image](https://user-images.githubusercontent.com/3986896/104939421-4d3aa980-59a8-11eb-9318-026ff85759c7.png)

The 2 versions appear correctly in these pages
- Public libraries
- My libraries
- Published monomers

However only version 1 appears in the 'My monomers' page. Version 2 doesn't seem to have any monomers. 
![image](https://user-images.githubusercontent.com/3986896/104939583-807d3880-59a8-11eb-824e-b7291fea9a6d.png)

**Comment by elrashid24** [comment]
Structurally correct:
The idea here is that we only want to view (and ultimately branch off) the latest version of the monomer set. 
For clarity, I can remove the filter and just display the version number you're looking at on the table itself?

**Comment by ClairePA** [comment]
Agreed.

**Comment by ClairePA** [comment]
Fixed as discussed. Close.
