### ISSUE TITLE
Manually created monomers do not have SMILES

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#39]
I manually create a monomer and draw the structure. A SMILES is not generated for the monomer. It should be. 
![image](https://user-images.githubusercontent.com/3986896/105704540-e0269700-5f06-11eb-9518-35576256ac60.png)

**Comment by elrashid24** [comment]
Resolved 1/28/20

**Comment by ClairePA** [comment]
The SMILES appears now, but the format for the attachment point is not quite right. For example this one
![image](https://user-images.githubusercontent.com/3986896/107065454-b574f200-67d4-11eb-8f67-d43f398167ea.png)

Should be `[H:1]C1=CC=CC=C1`
The attachment points must be numbered.

**Comment by ClairePA** [comment]
See the open source code for how to do this. It was been fully implemented there.

**Comment by ClairePA** [comment]
The SMILES are now fully capped and the connection point is not coded at all. I get

`BrC1=C(C)C2=C(C=C1)C(O)=CC=C2`

When I should have 

`BrC1=C(C)C2=C(C=C1)C[OH:1]=CC=C2`

**Comment by scilligence** [comment]
I remember that the reason to use [H:#] instead of [R#] is standard SMILES doesn't support [R1], [R2] ... (Roger asked).  But R Cap should not be there.  So the conversion should be simply [R1] to [H:1], [R2] to [H:2] ....

**Comment by ClairePA** [comment]
The comment above is incorrect. See this example in the [webeditor](http://webeditor.openhelm.org/hwe/examples/MonomerLibApp.htm). 
![image](https://user-images.githubusercontent.com/3986896/121198168-d5dbb880-c869-11eb-8f92-f83845676ebb.png)

The R cap should be there and you cannot make an assumption that the start of the code will always be H.

**Comment by ClairePA** [comment]
Also, see this example where a manually created monomer has an OH capping group. The SMILES is generated by the code and reflects the definition so the code to do this **must** be in the opensource tool somewhere. 

![image](https://user-images.githubusercontent.com/3986896/121200010-4d5e1780-c86b-11eb-83ab-f94d31b6b0e9.png)

**Comment by scilligence** [comment]
1. Will that SMILES be valid?
2. Some company uses custom CAP, e.g. Allyl.  Will that be encoded there as well?

**Comment by ClairePA** [comment]
Open Babel accepts it as does ChemDraw.
![image](https://user-images.githubusercontent.com/3986896/121204261-ad09f200-c86e-11eb-9364-82d234a5afe8.png)
2. We only need to include the examples the tool allows. Just H and OH covers nearly all the examples.

**Comment by ClairePA** [comment]
OK, let's have all the connection points in the SMILES as [H:n]. We will not ask the tool to create [OH:n] connection points.

**Comment by ClairePA** [comment]
Confirmed fixed.
