### ISSUE TITLE
Dialogue box should not contain text boxes for information that is not captured or used, 

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#4]
Monomer.org captures only minimal information about a user, however the display shows additional fields with no way of entering information into them. The extra fields should be removed from the display if they are not going to be used. 

![image](https://user-images.githubusercontent.com/3986896/82230395-94593200-9923-11ea-80ff-79a3c4dc05c3.png)

**Comment by elrashid24** [comment]
Addressed:
![image](https://user-images.githubusercontent.com/46327483/92600775-00b4c400-f27a-11ea-8d58-8e47f9d91319.png)

**Comment by ClairePA** [comment]
Confirmed fixed.
