### ISSUE TITLE
User email adresses are not saved

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#5]
I create a user, I enter the required information including the email address and save. 
I view the user later, the email address is not displayed in the box provided. 

I edit the user, add the email and save.
I open the user information by clicking the edit button and the email address is still not shown in the box provided. 

![image](https://user-images.githubusercontent.com/3986896/82233095-5f4ede80-9927-11ea-86fd-165779576057.png)

**Comment by elrashid24** [comment]
Addressed:
![image](https://user-images.githubusercontent.com/46327483/92600857-17f3b180-f27a-11ea-8f2c-c9974c8d7e63.png)

**Comment by ClairePA** [comment]
Confirmed fixed.
