### ISSUE TITLE
Error recognizing public library name

### ISSUE THREAD

**Issue by TianhongZhang** [PistoiaHELM/monomer.org#52]
In the public home, when I selected 'Test_v1_1' as my library, and tried to parse the default HELM string, I got an error (see attached) saying 'Invalid Column Name v1'. It worked with the library 'Another_1'.  If library names can't contain underscore, this should be caught during library creation time, rather than later. 

![Screen Shot 2021-03-25 at 7 21 04 AM](https://user-images.githubusercontent.com/3718858/112465584-467b3a80-8d3b-11eb-9bbc-05981fa6e15c.png)

**Comment by elrashid24** [comment]
Correct. This error will now be caught when before a library is saved

**Comment by ClairePA** [comment]
The invalid column name error no longer occurs, but the monomers in the set are not recognised. I will create a different issue to record this.
