### ISSUE TITLE
Public Home Screen View

### ISSUE THREAD

**Issue by TianhongZhang** [PistoiaHELM/monomer.org#53]
In addition to managing HELM monomers, one of the key functions of monomer.org would be a home for casual users to interpret their HELM strings. Say they get a HELM string from a collaborator, they want to know its structure and molecular properties. They can come to the site, paste in the HELM, and we will display all relevant info in a card view on the home page. This is not the behavior I am seeing now. When I hit the 'Parse' button, it takes me to the 'Editor' page, where only the structure is shown in the editor. 

Is the card view implemented somewhere else? I think it's important to have this function on the home page. We can put a link on the card to the editor page, but that's a secondary step. In the card view, we only want to show the image of the structure along with molecular properties and library info, we don't want to see the editor toolbar. 

Now about the home page. These are more questions than requests to change. We have three actionable UI components on the page: Library Dropdown list, HELM string text box and Parse button. Should we label the first two so that new users know what they are? Should we change 'Parse' to 'Interpret' on the button? Also, if we want to show multiple versions of the library in the dropdown list, can we use a cascading list?

**Comment by ClairePA** [comment]
Issues addressed in other reports. Suggest close this one and track in individual points separately.
