### ISSUE TITLE
A monomer appears to be detached from a library 

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#54]
If I click on the top level in the libraries navigation box, a monomer is displayed which is not associated with a library. I don't know how this got here, but worth investigating. 

![image](https://user-images.githubusercontent.com/3986896/112472403-fd3fe080-8d64-11eb-89e3-e12966edf55c.png)

**Comment by elrashid24** [comment]
Edge case, seems to be from legacy data. Does not reoccur with clean DB as monomers cannot be saved without a libraryid
