### ISSUE TITLE
Filtering doesn't work at all on the published monomers page

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#56]
Nothing happens when I try. 

![image](https://user-images.githubusercontent.com/3986896/112473838-c66aca00-8d66-11eb-81a8-b763a051b12d.png)

**Comment by elrashid24** [comment]
The filter boxes seem to be working. Filtering by version works as well, however if version "0" is entered, it defaults to version 1 since there is no version 0. The assumption is that users want to view the first published version.

**Comment by ClairePA** [comment]
My mistake. Close.
