### ISSUE TITLE
Monomer Library Versioning

### ISSUE THREAD

**Issue by TianhongZhang** [PistoiaHELM/monomer.org#57]
At this point, we have three public libraries in our testing environment (See screen shot below). From the top Public Libraries table, I can see the library 'Another Test' has three versions. If I select this library in the table, its details and published monomers are shown in the bottom tabs. I assume these are version 3 specific. 

Now how do I get the details and published monomers for Version 2 or 1? I am thinking about monomer library versioning the same way as software package versioning. For any given version, I should be able to get the details for it. In the library table, can we list out all versions as hyperlinks for each library, and clicking on each version link will show the details in the two tabs below. In other words, make the two bottom tabs library version specific, instead of library specific.

BTW, the library table pagination seems to be off. It shows two pages, even though we have only one.

![Screen Shot 2021-03-25 at 8 42 46 AM](https://user-images.githubusercontent.com/3718858/112474545-269d4400-8d46-11eb-8703-830faac114ba.png)

**Comment by ClairePA** [comment]
Issues covered in other defects. Propose close.
