### ISSUE TITLE
Library monomers not recognised if there is an underscore in the name

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#63]
If a library has an underscore in its name, the monomers are not recognised. For example, I get an error for this library even though the monomers in the HELM string exist.

![image](https://user-images.githubusercontent.com/3986896/114405098-3c13ca00-9b9e-11eb-8f2e-1393263414a7.png)

But all is fine with the same HELM string where the library name does not include an underscore. 
![image](https://user-images.githubusercontent.com/3986896/114405846-f73c6300-9b9e-11eb-87ea-ec290a5a6254.png)

If underscores are not allowed, the library creator should be prevented from saving it.

**Comment by ClairePA** [comment]
Not fixed. Behaviour is the same as before,.

**Comment by elrashid24** [comment]
Let me know if this one is confirmed close, I believe it was addressed

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
