### ISSUE TITLE
Monomer log doesn't do anything

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#67]
There is a log tab on the monomers page, but I can't make it display anything. 
![image](https://user-images.githubusercontent.com/3986896/117681597-2e0b9600-b1aa-11eb-966d-2de49ade1a6e.png)

Is this logging anything? What is it supposed to do?

**Comment by elrashid24** [comment]
It's meant to be sort of an audit trail for each monomer-basically it's history. I will look into why it is not being displayed.

**Comment by ClairePA** [comment]
I would just remove it. Logging would be nice, but I think we can leave until after this release.

**Comment by elrashid24** [comment]
Table removed.

**Comment by elrashid24** [comment]
Accidentally closed-confirm fix first.

**Comment by ClairePA** [comment]
Confirmed fixed.
