### ISSUE TITLE
N.A. should be changed to Natural Analog

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#7]
When adding a new monomer manually, the second text box is named N.A. This should be renamed 'Natural Analog' as it is confusing. It looks too much like 'Not Applicable'.

![image](https://user-images.githubusercontent.com/3986896/82244885-dab98b80-9939-11ea-97f2-a2b59ee0d4a9.png)

**Comment by elrashid24** [comment]
Addressed:
![image](https://user-images.githubusercontent.com/46327483/92602981-cdbfff80-f27c-11ea-9911-5a26a434acce.png)

**Comment by ClairePA** [comment]
Confirmed fixed. Close
