### ISSUE TITLE
The legal section in the footer should include links to the relevant documents

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#73]
This section needs to be updated.

![image](https://user-images.githubusercontent.com/3986896/117851502-4baa2f80-b27e-11eb-96a2-bcc8036b2b3c.png)

The privacy statement link go to the Pistoia privacy statement: [https://www.pistoiaalliance.org/online-privacy-statement/](url)

The `contract and legal notice` text should be removed. 
The `terms of use` text should link to a document I will supply as soon as our lawyers have signed off on it. 

The copyright notice should be removed.

**Comment by ClairePA** [comment]
Post meeting note - Copyright notice to be removed and the blue section to go to the end of the page. 
Use this logo (NB linked file) in the blue bar. I can get alternative formats/resolutions if necessary. 

![PistoiaAlliance_compact_white_RGB](https://user-images.githubusercontent.com/3986896/118503323-6ff48900-b722-11eb-9524-d92a1b7b761b.png)

**Comment by elrashid24** [comment]
Please confirm that document link is correct in the footer.
Will extend height of footer across all pages.

**Comment by ClairePA** [comment]
The document link is correct. I will leave this open until the other issues are resolved.

**Comment by ClairePA** [comment]
The logo in the footer doesn't seem to display. Do you need a different file type? We have a range of options. 
![image](https://user-images.githubusercontent.com/3986896/121678032-9356ed80-caae-11eb-84dd-bac80f2c4bd3.png)

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
