### ISSUE TITLE
Editor page changes

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#79]
Sort out the function call, so it isn't trying to display the mol wt/form in the same way as on the Home page. 
Remove the HELM string box and the view box.

![image](https://user-images.githubusercontent.com/3986896/118506052-e2666880-b724-11eb-8980-3ad9e950a27d.png)

Ensure the monomers in the selected library are available in the editor. 

Remove the ‘what can I do..’ boxes and ‘want to know more…’ 
![image](https://user-images.githubusercontent.com/3986896/118506236-0de95300-b725-11eb-832b-0403cf62d813.png)

**Comment by elrashid24** [comment]
Editor now defaults to page w/pop up window. Currently undergoing refinement to include library dropdown

**Comment by ClairePA** [comment]
Looks much better. I will close this issues and open another one to track the library drop down issue.
