### ISSUE TITLE
Monomer filtering on name and symbol is exact match and not 'contains'

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#8]
Filtering on the name and symbol should be 'contains' and not exact match. 

![image](https://user-images.githubusercontent.com/3986896/82314934-71ca2600-99c2-11ea-9efb-deb10cdd68bb.png)

**Comment by elrashid24** [comment]
Addressed:
![image](https://user-images.githubusercontent.com/46327483/92601361-b718a900-f27a-11ea-89f9-50bea812f6a4.png)



![image](https://user-images.githubusercontent.com/46327483/92602863-aff29a80-f27c-11ea-8f13-41b3dfca6fa5.png)

**Comment by ClairePA** [comment]
Seems to be better for the 'my monomers' list, but not for the 'published monomers' list. Are these different forms, if so, why?

**Comment by ClairePA** [comment]
Also, it seems to be 'starts with' not 'contains' 
![image](https://user-images.githubusercontent.com/3986896/96741699-009bfe00-13ba-11eb-8522-781393e7bbf3.png)
with no filtering
![image](https://user-images.githubusercontent.com/3986896/96741756-17425500-13ba-11eb-97a0-dccf65321f88.png)

**Comment by elrashid24** [comment]
Resolved

**Comment by ClairePA** [comment]
Still seems to be a problem. See example below:
![image](https://user-images.githubusercontent.com/3986896/104927788-c088ef00-5999-11eb-953c-e1e45207c573.png)

![image](https://user-images.githubusercontent.com/3986896/104927880-e2827180-5999-11eb-8708-e9a35420bc21.png)

**Comment by elrashid24** [comment]
Looks like it's working, but looking at your example with "Cyano" it'snot returning results because the search looks for names that start or end with your match.
For example if you were to search 5-cy, it hit.

If this is a big issue, I can implement an auto suggest feature for the search query. But even then, you'd have to at least start with correct character. 

Let me know what you think.

**Comment by ClairePA** [comment]
I do think this is a big issue as there will be many examples where you really do need a true 'contains' query. Surely this is a standard regular expression query where the regular expression is `.*'string to be searched'.*`  or whatever the syntax is in whatever you are using?

**Comment by ClairePA** [comment]
Fixed. Close.
