### ISSUE TITLE
Natural Analog box should not allow free text 

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/monomer.org#9]
I can enter any text I want into the natural analog field. The input form should only allow the symbols for the natural monomers for that polymer type or X.
 
![image](https://user-images.githubusercontent.com/3986896/84054068-bb4ad700-a9aa-11ea-8af4-fdd953814b9d.png)

**Comment by elrashid24** [comment]
Addressed (pending approval):
![image](https://user-images.githubusercontent.com/46327483/92600952-33f75300-f27a-11ea-92f2-30ab2e3a3b9a.png)

**Comment by ClairePA** [comment]
Fixed when you first create a monomer, but the drop down doesn't appear if you subsequently edit the monomer. Also, if you type the natural analogue and try to save you get the following error.

![image](https://user-images.githubusercontent.com/3986896/96509249-a54ffb80-1253-11eb-958f-03c18b94a426.png)

**Comment by ClairePA** [comment]
Some more notes:
The error above only appears if you edit the monomer in the 'unpublished monomer' list now. The monomer section appears to work correctly. 

CHEM monomers have a null or '-' as their natural analogue. This should be allowed. 
The only natural analogues for RNA are C G T U A P R D.

**Comment by elrashid24** [comment]
We will be changing the N.A. from a dropdown list back to free text & validating upon save. Agreed in meeting 1-08-2021.

**Comment by ClairePA** [comment]
Closing this issue as monomer validation on save is described in issue #26
